---

name: update-flake-lock

on:
  workflow_dispatch:  # allows manual triggering
  schedule:
    - cron: '0 5,17 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/update-flake-lock@v24
        id: update
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          nix-options: --debug --log-format raw
          pr-title: "Update flake.lock"  # Title of PR to be created
          pr-labels: |                   # Labels to be set on the PR
            dependencies
            automated
      - run: |
          if [ -n "${{ steps.update.outputs.pull-request-number }}" ]; then
            gh pr merge --auto --rebase ${{ steps.update.outputs.pull-request-number }}
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
